services:
  onair_db:
    image: mysql:8.4.3
    container_name: onair_db
    volumes:
      - onair-db-data:/var/lib/mysql
    env_file:
      - .env
    networks:
      - onair-network
      - monitoring
    ports:
      - "9523:3306"

networks:
  onair-network:
    driver: bridge
    name: onair-network
  monitoring:
    driver: bridge
    name: monitoring

volumes:
  onair-db-data: