services:
  langchain:
    image: langchain:latest
    container_name: langchain
    env_file:
      - .env
    networks:
      - kafka_kafka_network

networks:
  kafka_kafka_network:
    external: true