services:
  nginx:
    image: nginx:1.27
    container_name: nginx-certbot
    restart: unless-stopped
    volumes:
      - /exec/cert:/etc/nginx/conf.d
      - /exec/cert/certbot/conf:/etc/letsencrypt
      - /exec/cert/certbot/www:/var/www/certbot
    ports:
      - "80:80"   # HTTP 포트 (Certbot의 HTTP-01 챌린지에서 필요)
      - "443:443" # HTTPS 포트

  certbot:
    image: certbot/certbot  # Certbot 최신 이미지
    container_name: certbot
    command: certonly --webroot --webroot-path=/var/www/certbot --email jinee9523@gmail.com --agree-tos --no-eff-email -d ele.on-air.me -d gance.on-air.me

    volumes:
      - /exec/cert/certbot/conf:/etc/letsencrypt
      - /exec/cert/certbot/www:/var/www/certbot
    depends_on:
      - nginx