services:
  main_server:
    image: parkdonghyeon/main_image:latest
    env_file:
      - .env
    networks:
      - onair-network
      - nginx
    container_name: main_server

  media_server:
    image: parkdonghyeon/media_image:latest
    env_file:
      - .env
    networks:
      - onair-network
      - nginx
    volumes:
      - /streaming_channels:/app/media/streaming_channels
    container_name: media_server

networks:
  onair-network:
    external: true

  nginx:
    external: true