version: '3.8'

services:
  main_server:
    image: parkdonghyeon/main_image:latest
    env_file:
      - .env
    networks:
      - onair-overlay-network
      - nginx
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  media_server:
    image: parkdonghyeon/media_image:latest
    env_file:
      - .env
    networks:
      - onair-overlay-network
      - nginx
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
    
networks:
  onair-overlay-network:
    external: true

  nginx:
    external: true