services:
  nginx:
    image: nginx:1.27
    container_name: nginx
    volumes:
      - certbot_data:/etc/nginx/certbot  # 인증서 볼륨을 공유하여 모든 노드에서 접근 가능하게 함
      - /exec/nginx/conf:/etc/nginx/conf.d
      - /exec/cert/certbot/conf:/etc/letsencrypt
      - /exec/cert/certbot/www:/var/www/certbot
    networks:
      - nginx
    ports:
      - "443:443" # HTTPS 접근
    depends_on:
      - main_server
      - media_server

  main_server:
    image: parkdonghyeon/main_image:latest
    env_file:
      - .env
    networks:
      - onair-network
      - kafka-network
      - nginx
    container_name: main_server

  media_server:
    image: parkdonghyeon/media_image:latest
    env_file:
      - .env
    networks:
      - onair-network
      - kafka-network
      - nginx
    volumes:
      - /app/media/data:/media/streaming_channels
    container_name: media_server


  station_server:
    image: parkdonghyeon/station_image:latest
    env_file:
      - .env
    networks:
      - onair-network
      - kafka-network
    container_name: station_server
    volumes:
      - /app/streaming/data:/medias

networks:
  onair-network:
    external: true
  nginx:
    driver: bridge
    name: nginx
  kafka-network:
    external: true

volumes:
  certbot_data: