version: '3.8'

configs:
  create-topics-script:
    external: true

services:
  kafka-init:
    image: confluentinc/cp-kafka:7.4.0
    networks:
      - onair-network
    configs:
      - source: create-topics-script
        target: /create-topics.sh
    command: >
      sh -c "
      until nc -z onair_zookeeper-1 2181 && nc -z onair_zookeeper-2 2181 && nc -z onair_zookeeper-3 2181; do
        echo 'Waiting for Zookeeper...';
        sleep 5;
      done;
      sh /create-topics.sh
      "

networks:
  onair-overlay-network:
    external: true