version: '3.8'

services:
  zookeeper-1:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_SERVER_ID: 1
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_SERVER: "onair_zookeeper-1:2888:3888;onair_zookeeper-2:2888:3888;onair_zookeeper-3:2888:3888"
    networks:
      - onair-overlay-network
    volumes:
      - zookeeper_data_1:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  zookeeper-2:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_SERVER_ID: 2
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_SERVER: "onair_zookeeper-1:2888:3888;onair_zookeeper-2:2888:3888;onair_zookeeper-3:2888:3888"
    networks:
      - onair-overlay-network
    volumes:
      - zookeeper_data_2:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  zookeeper-3:
    image: confluentinc/cp-zookeeper:7.4.0
    environment:
      ZOOKEEPER_SERVER_ID: 3
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      ZOOKEEPER_INIT_LIMIT: 10
      ZOOKEEPER_SYNC_LIMIT: 5
      ZOOKEEPER_SERVER: "onair_zookeeper-1:2888:3888;onair_zookeeper-2:2888:3888;onair_zookeeper-3:2888:3888"
    networks:
      - onair-overlay-network
    volumes:
      - zookeeper_data_3:/data
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

networks:
  onair-overlay-network:
    external: true

volumes:
  zookeeper_data_1:
    driver: local
  zookeeper_data_2:
    driver: local
  zookeeper_data_3:
    driver: local